### ISSUE TITLE
Support for version 10.x

### ISSUE THREAD

**Issue by Marciobds** [Leshkens/orchid-help-hint-layout#2]
![image](https://user-images.githubusercontent.com/5437204/139332118-f305a25f-afd7-4be8-b947-2e37a531d64f.png)

**Comment by Leshkens** [comment]
Hi. I'll fix it when I have time. Or you can send PR

**Comment by Leshkens** [comment]
[v3.0.0 Release ](https://github.com/Leshkens/orchid-help-hint-layout/releases/tag/v3.0.0)
